# Aims and Intended Learning Outcomes

The Learning outcomes for the placement year are

* To learn how to operate in a professional environment
* To apply the skills and knowledge you've learned at University in the workplace
* To grow as a professional by seeking out development opportunities to acquire new skills and knowledge in the workplace
*  To meet (or exceed) the expectation of your employer, as set out in your contract of employment
* To describe your development as a professional in a short written report

Some of this will involve developing skills and knowledge beyond your University curriculum such as softer skills and digital capabilities, described below.

## Developing your digital capabilities
Throughout your time at The University of Manchester you will be supported to develop the digital capabilities needed for your studies and future careers. Your placement experience will provide you with further authentic digital development opportunities. The following information is intended to help
you record and articulate your capabilities, supporting your development and further enhancing your employability.

## What are digital capabilities?
Digital capabilities enable us to ‘live, learn and work in a digital society.’ This profile provides further information about the capabilities University students might expect to develop; it is important to contextualise these, so they are relevant to you and your studies.

## Exploring your digital capabilities

The Jisc Discovery tool is a supportive online tool, that can help you understand and develop your digital capabilities. By completing a question set within the tool you can gain a personalised report that includes
links to suggested resources in the tool’s resource bank to support your further development. It is recommended that you repeat the question sets annually, to recognise your progress across the different elements of digital capability. You can access the Discovery tool through 

*  My Learning Essentials: Develop your digital capabilities resource. [education.library.manchester.ac.uk/none-programme-content/digital-capabilities/](https://www.education.library.manchester.ac.uk/none-programme-content/digital-capabilities/)
* My Skills Development – on CareerConnect [careers.manchester.ac.uk/findjobs/skills/myskills](https://www.careers.manchester.ac.uk/findjobs/skills/myskills/)

These resources support you in reflecting on your development on your reports - providing an action plan template for you to complete.

For placement students, we recommend taking the:

*  ‘Current student’ digital capability question set, which provides an in-depth exploration of your digital confidence and experience.
*  ‘Digital skills in AI and generative AI’ question set, which also has its own resource bank


## Recording your development
From work with employers, we know they value narratives around how you have developed your skills and capabilities through your studies. You can use the language from your Discovery tool reports to update your CV / online professional profile to help you record your digital development. This blog by the Careers Service can further support you with capturing and articulating the capabilities you develop during your placement. [@conway]