# So, you're going on placement? {#starting}
Congratulations, if you’ve accepted a job offer and its been approved, you’re ready to start your placement.

## Key dates {#keydates} 

Here are a list of all the key dates before, during and after yoyr placement

Obtain and submit plans for formal academic approval deadline, 31 August 2025.
Once you start your job, there are three key dates, four if you are working outside the UK:

1. FIRST CHECK-IN MEETING Initial one-to-one check-in meeting, 30 September – 31 October 2025. Students should coordinate with allocated academic to arrange a suitable time and date.
1. SECOND CHECK-IN MEETING Second check-in meeting for students on placement outside the UK (only) 20-31 January 2026 Students should coordinate with allocated academic to arrange a suitable time and date.
1. MANAGER, TUTOR & YOU MEETING: Academic tutor, personal tu & stutordent meeting,** 31 March – 25 April 2026**. Students should coordinate with academic, supervisor/line manager to arrange a suitable time and date. If you are not able to arrange a date during this time period, the meeting needs to take place before the end of your placement year
1. PLACEMENT REPORT SUBMISSION: End of welcome week 2026, submit placement report using the form described in section 6.1