# Tutor meeting guide for Industrial Experience {#tutors}

Information for personal tutors (academic staff) interviewing students (and their managers) on their Industrial Experience placement.

## Purpose of the meeting {#purpose}
The purpose of the meeting between you (the tutor), your tutee (the student) and their manager(s) is to: 

1. Find out what they have been doing, see section \@ref(what) 
1. Get students to reflect on what they’ve done well, with their manager, see section \@ref(www) 
1. Get students to reflect on what they could do better, with their manager, see section \@ref(ebi) 
1. Record that the meeting has taken place, using the [bit.ly/placement-visit-form](bit.ly/placement-visit-form) [@visitform]
1. Any other business? See section \@ref(aob) 

Most employers can do these visits remotely via Microsoft Teams, Zoom or similar video conferencing software.

Once you’ve visited your tutees, please fill in the short tutees form at [bit.ly/placement-visit-form](bit.ly/placement-visit-form) [@visitform] to capture this information and so that we know which students have been visited. The meetings usually last somewhere between 15 and 30 minutes, we've a suggested agenda below.

## What have you been doing? {#what}

Ask the student to describe what they have been doing since they started on placement and how that fits into the wider organisation they are a part of. Some students need more prompting than others, here are some suggestions:

* Tell me about your employer and the products or services they provide?
* Which products or services have you been working on?
* What methodologies and tools have you been using?
* What have you been surprised by since you started work?

Most employers can do these visits remotely via Microsoft Teams, Zoom or similar video conferencing software.


## What Went Well (WWW)? {#www}

What is going well? Ask the student first, then their manager. Compare results.


* Are there any projects or achievements you are particularly proud of (ask student first, then their manager) compare results
* What skills or knowledge have you managed to build so far, include soft & hard skills?

## Even Better If (EBI)? {#ebi}

What do they need to improve 

* What areas have you identified for improvement in the future (ask student first, then their manager) compare results
* How are you planning to develop these skills? Include soft & hard skills
* Are there any other things you want to work on before the placement finishes?

## Any Other Business (AOB) {#aob}

This is an opportunity to remind students who don't read their email that: 

*  They need to choose a 3rd year honours project: This is a good opportunity to check that the student has chosen or proposed a final year project. They’ve already received information about this from Terence Morley, but it might help to remind them.
* They need to write a placement report:  
    + For Bachelors students, there’s a short placement report form to fill in by September at [forms.office.com/e/K1gAuWrnex](https://forms.office.com/e/K1gAuWrnex) (UoM login required)
    + For MEng students, the details for MEng report submission see COMP40901 
* Ask the employer if they are interested in joining our industry club, careers fairs etc record any contact details (names, email addresses) at [bit.ly/placement-visit-form](bit.ly/placement-visit-form)


## Scheduling meetings using Outlook {#schedule}

Students typically finish their placements anytime between June and August, so it’s usually best to have the meeting before end of May or early June.

You may find the tools in Outlook useful for scheduling the meeting, there are a few ways of doing this:

* [outlook.office.com/bookwithme](https://outlook.office.com/bookwithme)
* Bookings with me is a service you may need to ask IT services to activate, see [www.itservices.manchester.ac.uk/ourservices/popular/microsoft365/bookings](https://www.itservices.manchester.ac.uk/ourservices/popular/microsoft365/bookings/)
* an alternative is to use a scheduling poll, works on Windows, Mac and the browser version of outlook.office.com [@poll]